#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999

export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.composer/vendor/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH

export PATH=/usr/local/opt/python@3.9/bin:$PATH
export PATH=/usr/local/bin/yarn:$PATH
export PATH=/usr/local/opt/mysql@5.7/bin:$PATH
export PATH=/usr/local/opt/node@12/bin:$PATH
