#!/bin/sh

# General aliases that I use everyday

alias cd='z'
alias vim='lvim'
alias venv='python3 -m venv'
alias n12='fnm use 12'
alias n14='fnm use 14'
alias n16='fnm use 16'

alias y="yarn"
alias ya="yarn add"
alias prettierd="prettier_d_slim"
alias gtop="gotop"

alias gcr='cd $(git root)'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# better ls
alias ls='lsd'
alias l='ls -Fla'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'

# easier to read disk
alias df='df -h'     # human-readable sizes

# get top process eating memory
alias psmem='ps aux | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps aux | sort -nr -k 3 | head -5'
alias whasmyip='dig +short myip.opendns.com @resolver1.opendns.com'
