#!/bin/sh

alias vim='lvim'
alias tmux='tmux -u'
alias venv='python3 -m venv'
alias vtop='vtop --theme nord --no-mouse'

alias y="yarn"
alias ya="yarn add"

# Paths
alias gcr='cd $(git root)'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# better ls
alias ls='lsd'
alias l='ls -Fla'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'

# easier to read disk
alias df='df -h'     # human-readable sizes

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
alias whasmyip='dig +short myip.opendns.com @resolver1.opendns.com'

alias dc='docker-compose'
alias dcr='dc run --rm'
