#!/bin/sh
# general
alias artisan='php artisan'
alias a='php artisan' # -- artisan
alias av='artisan -V'
alias acc='artisan clear-compiled'
alias ad='artisan down'
alias ae='artisan env'
alias ah='artisan help'
alias ai='artisan inspire'
alias al='artisan list'
alias ap='artisan preset'
alias as='artisan serve'
alias at='artisan tinker'
alias ati='artisan tinx'
alias au='artisan up'

#app
alias aanm='artisan app:name'

#auth
alias aacr='artisan auth:clear-resets'

# cache
alias accl='artisan cache:clear'
alias acfg='artisan cache:forget'
alias actb='artisan cache:table'

# config
alias acfcc='artisan config:cache'
alias acfcl='artisan config:clear'

# common
alias adbs='artisan db:seed'
alias aeg='artisan event:generate'
alias akg='artisan key:generate'

# make
alias amkau='artisan make:auth'
alias amkch='artisan make:channel'
alias amkcm='artisan make:command'
alias amkct='artisan make:controller'
alias amkctr='artisan make:controller -r'
alias amkev='artisan make:event'
alias amkex='artisan make:exception'
alias amkfc='artisan make:factory'
alias amkjb='artisan make:job'
alias amkls='artisan make:listener'
alias amkml='artisan make:mail'
alias amkmw='artisan make:middleware'
alias amkmg='artisan make:migration'
alias amkmd='artisan make:model'
alias amkmdm='artisan make:model -m'
alias amknf='artisan make:notification'
alias amkos='artisan make:observer'
alias amkpl='artisan make:policy'
alias amkpv='artisan make:provider'
alias amkrq='artisan make:request'
alias amkres='artisan make:resource'
alias amkrl='artisan make:rule'
alias amksd='artisan make:seeder'
alias amkts='artisan make:test'

# migrate
alias amg='artisan migrate'
alias amgf='artisan migrate --force'
alias amgs='artisan migrate --seed'
alias amgp='artisan migrate --pretend'
alias amgt='artisan migrate --env=testing'
alias amgfr='artisan migrate:fresh'
alias amgis='artisan migrate:install'
alias amgrf='artisan migrate:refresh'
alias amgrs='artisan migrate:reset'
alias amgrb='artisan migrate:rollback'
alias amgst='artisan migrate:status'

# notifications
alias anftb='artisan notifications:table'

# optimize
alias ao='artisan optimize'
alias aoc='artisan optimize:clear'
# package
alias apd='artisan package:discover'

# queue
alias aqf='artisan queue:failed'
alias aqft='artisan queue:failed-table'
alias aqfl='artisan queue:flush'
alias aqfg='artisan queue:forget'
alias aqls='artisan queue:listen'
alias aqrs='artisan queue:restart'
alias aqrt='artisan queue:retry'
alias aqtb='artisan queue:table'
alias aqwk='artisan queue:work'

# route
alias arcc='artisan route:cache'
alias arcl='artisan route:clear'
alias arls='artisan route:list'

# schedule
alias asfn='artisan schedule:finish'
alias asrn='artisan schedule:run'

# session
alias astb='artisan session:table'

# storage
alias asln='artisan storage:link'

# vendor
alias avpb='artisan vendor:publish'

# view
alias avcc='artisan view:cache'
alias avcl='artisan view:clear'

# horizon
alias ahz='artisan horizon'
alias ahzas='artisan horizon:assets'
alias ahzct='artisan horizon:continue'
alias ahzls='artisan horizon:list'
alias ahzps='artisan horizon:pause'
alias ahzpg='artisan horizon:purge'
alias ahzss='artisan horizon:snapshot'
alias ahzsv='artisan horizon:supervisor'
alias ahzsvs='artisan horizon:supervisors'
alias ahztm='artisan horizon:terminate'
alias ahzto='artisan horizon:timeout'
alias ahzwk='artisan horizon:work'

# passport
alias apspi='artisan passport:install'
alias apspc='artisan passport:client'
alias apspk='artisan passport:keys'

# old framework versions commands
alias amkcs='art_make console'
alias ahcm='artisan handler:command'
alias ahev='artisan handler:event'
alias aqss='artisan queue:subscribe'
alias afr='artisan fresh'

